// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SecurityMedicClient is the client API for SecurityMedic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityMedicClient interface {
	Join(ctx context.Context, in *Connect, opts ...grpc.CallOption) (SecurityMedic_JoinClient, error)
	Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Close, error)
}

type securityMedicClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityMedicClient(cc grpc.ClientConnInterface) SecurityMedicClient {
	return &securityMedicClient{cc}
}

func (c *securityMedicClient) Join(ctx context.Context, in *Connect, opts ...grpc.CallOption) (SecurityMedic_JoinClient, error) {
	stream, err := c.cc.NewStream(ctx, &SecurityMedic_ServiceDesc.Streams[0], "/proto.SecurityMedic/Join", opts...)
	if err != nil {
		return nil, err
	}
	x := &securityMedicJoinClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SecurityMedic_JoinClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type securityMedicJoinClient struct {
	grpc.ClientStream
}

func (x *securityMedicJoinClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *securityMedicClient) Publish(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Close, error) {
	out := new(Close)
	err := c.cc.Invoke(ctx, "/proto.SecurityMedic/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityMedicServer is the server API for SecurityMedic service.
// All implementations must embed UnimplementedSecurityMedicServer
// for forward compatibility
type SecurityMedicServer interface {
	Join(*Connect, SecurityMedic_JoinServer) error
	Publish(context.Context, *Message) (*Close, error)
	mustEmbedUnimplementedSecurityMedicServer()
}

// UnimplementedSecurityMedicServer must be embedded to have forward compatible implementations.
type UnimplementedSecurityMedicServer struct {
}

func (UnimplementedSecurityMedicServer) Join(*Connect, SecurityMedic_JoinServer) error {
	return status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedSecurityMedicServer) Publish(context.Context, *Message) (*Close, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedSecurityMedicServer) mustEmbedUnimplementedSecurityMedicServer() {}

// UnsafeSecurityMedicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityMedicServer will
// result in compilation errors.
type UnsafeSecurityMedicServer interface {
	mustEmbedUnimplementedSecurityMedicServer()
}

func RegisterSecurityMedicServer(s grpc.ServiceRegistrar, srv SecurityMedicServer) {
	s.RegisterService(&SecurityMedic_ServiceDesc, srv)
}

func _SecurityMedic_Join_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Connect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SecurityMedicServer).Join(m, &securityMedicJoinServer{stream})
}

type SecurityMedic_JoinServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type securityMedicJoinServer struct {
	grpc.ServerStream
}

func (x *securityMedicJoinServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _SecurityMedic_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityMedicServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SecurityMedic/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityMedicServer).Publish(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityMedic_ServiceDesc is the grpc.ServiceDesc for SecurityMedic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityMedic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SecurityMedic",
	HandlerType: (*SecurityMedicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _SecurityMedic_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Join",
			Handler:       _SecurityMedic_Join_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/proto.proto",
}
